# Configuration H2 Database
spring.datasource.url=jdbc:h2:./data/catastrophe_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration - Création automatique des tables
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (optionnel, pour voir la DB)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
